-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 3,
        gaps_in = 3,
        gaps_out = 8,
        layout = "scrolling",
    },
    misc = {
        vrr = 0,
    },
})

-- Monitors
hl.monitor({
    output = "DP-2",
    disabled = false,
    mode = "2560x1440@164.96Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("spotify"))
hl.unbind("SUPER + SHIFT + J")
hl.bind("SUPER + SHIFT + J", hl.dsp.exec_cmd("hyprmod"))
