--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jordan/Pictures/Wallpapers/hornet_groddo.png"

-- Special
background="#020705"
foreground="#c9dca9"
cursor="#c9dca9"

-- Colors
color0="#020705"
color1="#275646"
color2="#346D4C"
color3="#4D7450"
color4="#4B942E"
color5="#5E9A5F"
color6="#8DB064"
color7="#c9dca9"
color8="#8c9a76"
color9="#275646"
color10="#346D4C"
color11="#4D7450"
color12="#4B942E"
color13="#5E9A5F"
color14="#8DB064"
color15="#c9dca9"
