# Shell variables
# Generated by 'wal'
wallpaper='/home/jordan/Pictures/Wallpapers/hornet_groddo.png'

# Special
background='#020705'
foreground='#c9dca9'
cursor='#c9dca9'

# Colors
color0='#020705'
color1='#275646'
color2='#346D4C'
color3='#4D7450'
color4='#4B942E'
color5='#5E9A5F'
color6='#8DB064'
color7='#c9dca9'
color8='#8c9a76'
color9='#275646'
color10='#346D4C'
color11='#4D7450'
color12='#4B942E'
color13='#5E9A5F'
color14='#8DB064'
color15='#c9dca9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
