# Shell variables
# Generated by 'wal'
wallpaper='/home/jordan/Pictures/Wallpapers/hornet_groddo.png'

# Special
background='#010402'
foreground='#9ca19e'
cursor='#9ca19e'

# Colors
color0='#010402'
color1='#214944'
color2='#593c35'
color3='#366d42'
color4='#7f8c7c'
color5='#67a35c'
color6='#84a484'
color7='#9ca19e'
color8='#3a443e'
color9='#214944'
color10='#593c35'
color11='#366d42'
color12='#7f8c7c'
color13='#67a35c'
color14='#84a484'
color15='#9ca19e'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
