--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jordan/Pictures/Wallpapers/hornet_groddo.png"

-- Special
background="#010402"
foreground="#9ca19e"
cursor="#9ca19e"

-- Colors
color0="#010402"
color1="#214944"
color2="#593c35"
color3="#366d42"
color4="#7f8c7c"
color5="#67a35c"
color6="#84a484"
color7="#9ca19e"
color8="#3a443e"
color9="#214944"
color10="#593c35"
color11="#366d42"
color12="#7f8c7c"
color13="#67a35c"
color14="#84a484"
color15="#9ca19e"
